### ISSUE TITLE
Fix Vue container - Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by WGierke** [concept-to-clinic/concept-to-clinic#113]
Currently, when attempting to build the project using `docker-compose -f local.yml build && docker-compose -f local.yml up`, the Vue container dies while trying to build the front-end.

## Expected Behavior
Building and firing up the containers should be enough to let the Vue container serve at http://localhost:8080.

## Current Behavior
Firing up the Vue container fails with `Error: Cannot find module 'chalk'`:

```
➜  concept-to-clinic git:(master) ✗ sudo docker-compose -f local.yml build && sudo docker-compose -f local.yml up
[...]
vue_1         | npm info it worked if it ends with ok
vue_1         | npm info using npm@5.3.0
vue_1         | npm info using node@v8.5.0
vue_1         | npm info lifecycle c2c-vue@1.0.0~predev: c2c-vue@1.0.0
vue_1         | npm info lifecycle c2c-vue@1.0.0~dev: c2c-vue@1.0.0
vue_1         | 
vue_1         | > c2c-vue@1.0.0 dev /app/frontend
vue_1         | > node build/dev-server.js
vue_1         | 
vue_1         | module.js:529
vue_1         |     throw err;
vue_1         |     ^
vue_1         | 
vue_1         | Error: Cannot find module 'chalk'
vue_1         |     at Function.Module._resolveFilename (module.js:527:15)
vue_1         |     at Function.Module._load (module.js:476:23)
vue_1         |     at Module.require (module.js:568:17)
vue_1         |     at require (internal/module.js:11:18)
vue_1         |     at Object.<anonymous> (/app/frontend/build/check-versions.js:1:75)
vue_1         |     at Module._compile (module.js:624:30)
vue_1         |     at Object.Module._extensions..js (module.js:635:10)
vue_1         |     at Module.load (module.js:545:32)
vue_1         |     at tryModuleLoad (module.js:508:12)
vue_1         |     at Function.Module._load (module.js:500:3)
vue_1         | npm info lifecycle c2c-vue@1.0.0~dev: Failed to exec dev script
vue_1         | npm ERR! code ELIFECYCLE
vue_1         | npm ERR! errno 1
vue_1         | npm ERR! c2c-vue@1.0.0 dev: `node build/dev-server.js`
vue_1         | npm ERR! Exit status 1
vue_1         | npm ERR! 
vue_1         | npm ERR! Failed at the c2c-vue@1.0.0 dev script.
vue_1         | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
vue_1         | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
vue_1         | 
vue_1         | npm ERR! A complete log of this run can be found in:
vue_1         | npm ERR!     /root/.npm/_logs/2017-09-13T16_15_20_703Z-debug.log
```

## Possible Solution
When I manually cd into frontend, install the dependencies using `npm install` and run `docker-compose -f local.yml up` again, it works.

## Steps to Reproduce
Check out the current master  
`git reset --hard origin/master`
Remove all files and folders that are not explicitly tracked by Git (such as npm build files or modules)  
`sudo git clean -x -i -d`
Build and start the docker containers
`sudo docker-compose -f local.yml build && sudo docker-compose -f local.yml up`  
You should already see that the Vue container throws an error and exits.
When visiting http://localhost:8080/, you'll get a `Connection refused`.
Thus, we need to install the npm dependencies manually
`cd interface/frontend && npm install`  
Run `sudo docker-compose -f local.yml up` and visit localhost:8080 again - it should work now.

I'd appreciate any feedback - maybe I made a mistake while setting it up?

## Checklist before submitting
- [X] I have confirmed this using the officially supported Docker Compose setup using the `local.py` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [X] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [X] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [X] I provided **screenshots** where appropriate
- [X] I filled out all the relevant sections of this template

**Comment by isms** [comment]
@WGierke Can you delete any `node_modules` folder you have?

One hypothesis is that if those are getting put into the container with the volume mapping (`interface/frontend` on host -> `/app` on the container), they may be overriding the global npm install within the container.

**Comment by WGierke** [comment]
@isms I deleted all node_modules folders, removed all containers and built them from scratch. 
I'm still running into this issue. Can you reproduce it?

**Comment by isms** [comment]
@WGierke Yes, you're right, thanks for checking. I'm trying to research why the global install isn't working, will report back.

**Comment by isms** [comment]
@WGierke should be closed by 139d500 - can you check?

**Comment by WGierke** [comment]
@isms Works like a charm now. Thank you!

**Comment by isms** [comment]
Thanks for reporting.

**Comment by reubano** [comment]
Still getting this error. Anyone else?

**Comment by elnardu** [comment]
@reubano same
```
module.js:529
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/app/build/check-versions.js:2:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm info lifecycle @1.0.0~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-27T02_39_24_581Z-debug.log
```

**Comment by isms** [comment]
@reubano I was just able to successfully build `master` without this problem. Any updates?

**Comment by nwaughachukwuma** [comment]
Hey guys (@reubano and all) am getting this error on my Heroku App after CI/CD from GitLab to Heroku. Following is the gitlab-ci.yml script:

```
image: node:6

stages:
  - ver
  - init
  - tests
  - deploy

cache:
  paths:
    - node_modules/

ver:
  stage: ver
  script:
    - node --version
    - whoami
init:
  stage: init
  script:
    - npm install -g chalk
    - npm cache clean
    - rm -rf node-modules
    - npm install
    
run_tests:
 # needed for testing selenium on docker with java
  image: karthikiyengar/node-nightwatch:0.0.1
  stage: tests
  script:
    - sudo npm install
    - sudo npm test

deploy_staging:
  stage: deploy
  script:
    - npm install -g chalk
    - npm cache clean
    - rm -rf node-modules
    - npm install    
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/webapp-staging.git
    - git push heroku master
    - echo "Deployed to staging server"
  environment: staging
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - npm install -g chalk
    - npm cache clean
    - rm -rf node-modules
    - npm install
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/webapp.git
    - git push heroku master
    - echo "Deployed to production server"
  environment: production
  when: manual
  only:
    - master
```
Help will be greatly appreciated. Thanks
